(function(){
  const categories={expense:['Food & dining','Transport','Shopping','Bills & utilities','Health','Entertainment','Home','Education','Travel','Other'],income:['Salary','Freelance','Investments','Gift','Other']};
  const icons={'Food & dining':'◒',Transport:'↗',Shopping:'◇','Bills & utilities':'⌁',Health:'✚',Entertainment:'♫',Home:'⌂',Education:'▤',Travel:'✈',Other:'•',Salary:'↙',Freelance:'✧',Investments:'◌',Gift:'♡'};
  const colors=['#f2edff','#e9f6f1','#fff0e9','#edf4ff','#fff3de','#fceefa','#e8f6f8'];
  const demo=[
    {date:dateOffset(0),type:'expense',category:'Food & dining',note:'Lunch with colleagues',amount:420},
    {date:dateOffset(-1),type:'expense',category:'Transport',note:'Uber ride',amount:280},
    {date:dateOffset(-2),type:'income',category:'Salary',note:'Monthly salary',amount:85000},
    {date:dateOffset(-3),type:'expense',category:'Bills & utilities',note:'Electricity bill',amount:1850},
    {date:dateOffset(-4),type:'expense',category:'Shopping',note:'Household essentials',amount:2450},
    {date:dateOffset(-5),type:'expense',category:'Food & dining',note:'Groceries',amount:1380},
    {date:dateOffset(-6),type:'expense',category:'Entertainment',note:'Movie tickets',amount:680},
    {date:dateOffset(-8),type:'expense',category:'Health',note:'Pharmacy',amount:530},
    {date:dateOffset(-10),type:'income',category:'Freelance',note:'Side project',amount:3500},
    {date:dateOffset(-12),type:'expense',category:'Food & dining',note:'Dinner',amount:950},
    {date:dateOffset(-15),type:'expense',category:'Home',note:'Kitchen items',amount:1650},
    {date:dateOffset(-19),type:'expense',category:'Transport',note:'Fuel',amount:1700}
  ].map((t,i)=>Object.assign({id:'demo-'+i},t));
  function dateOffset(n){const d=new Date();d.setDate(d.getDate()+n);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
  const state={transactions:[],month:new Date(new Date().getFullYear(),new Date().getMonth(),1),goal:20000,backend:'demo',showAll:false,chartRange:'month'};
  const $=id=>document.getElementById(id);
  const money=n=>'₹'+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:0});
  const fmtDate=s=>new Date(s+'T00:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short'});
  const monthKey=d=>d.slice(0,7);
  const monthKeyFromDate=d=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0');
  function toast(s){const e=$('toast');e.textContent=s;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2300)}
  function openModal(id){$(id).classList.remove('hidden');document.body.style.overflow='hidden';if(id==='transactionModal')setTimeout(()=>$('amount').focus(),80)}
  function closeModal(id){$(id).classList.add('hidden');document.body.style.overflow=''}
  function showError(s){$('formError').textContent=s;$('formError').classList.remove('hidden')}
  async function request(path,options){const r=await fetch(path,options);let data={};try{data=await r.json()}catch(_){}if(!r.ok)throw new Error(data.error||'Request failed');return data}
  async function init(){
    const cats=$('category');cats.innerHTML=categories.expense.map(c=>'<option>'+c+'</option>').join('');$('date').value=dateOffset(0);$('today').textContent=new Date().toLocaleDateString('en-IN',{weekday:'short',day:'numeric',month:'short'});
    try{const auth=await request('/api/auth');if(auth.configured){state.backend='sheets';if(!auth.authenticated){$('loginModal').classList.remove('hidden');document.body.style.overflow='hidden';return;}const data=await request('/api/transactions');state.transactions=data.transactions||[];banner('Connected to your Google Sheet. <strong>Your entries sync across your devices.</strong>');}else{loadLocal();banner('Preview mode: <strong>sample entries are shown.</strong> Anything you add stays in this browser until Google Sheets is connected.');}}catch(_){loadLocal();banner('Preview mode: <strong>sample entries are shown.</strong> Anything you add stays in this browser until Google Sheets is connected.');}
    const saved=localStorage.getItem('pennywise_goal');if(saved)state.goal=Number(saved)||20000;render();
  }
  function banner(html){$('modeBanner').innerHTML=html;$('modeBanner').classList.remove('hidden')}
  function loadLocal(){state.backend='local';try{const d=JSON.parse(localStorage.getItem('pennywise_transactions')||'null');state.transactions=Array.isArray(d)?d:demo.slice();if(!d)localStorage.setItem('pennywise_transactions',JSON.stringify(state.transactions));}catch(_){state.transactions=demo.slice()}}
  function persistLocal(){localStorage.setItem('pennywise_transactions',JSON.stringify(state.transactions));}
  function inMonth(t,m){return monthKey(t.date)===monthKeyFromDate(m)}
  function render(){
    const mk=state.month.toISOString().slice(0,7), monthTx=state.transactions.filter(t=>inMonth(t,state.month)), expenses=monthTx.filter(t=>t.type==='expense'), incomes=monthTx.filter(t=>t.type==='income');
    const spend=expenses.reduce((s,t)=>s+Number(t.amount),0),income=incomes.reduce((s,t)=>s+Number(t.amount),0),saved=Math.max(0,income-spend),rate=income?Math.max(0,Math.round(saved/income*100)):0;
    $('monthLabel').textContent=state.month.toLocaleDateString('en-IN',{month:'long',year:'numeric'});$('balanceValue').textContent=money(income-spend);$('incomeValue').textContent=money(income);$('expenseValue').textContent=money(spend);$('incomeCount').textContent=incomes.length+' entr'+(incomes.length===1?'y':'ies');$('expenseCount').textContent=expenses.length+' entr'+(expenses.length===1?'y':'ies');$('savingsRate').textContent=rate+'%';$('savingsTrack').style.width=Math.min(rate,100)+'%';$('savingsHint').textContent=income?'Saved '+money(saved):'Add your income';$('balanceCaption').textContent=income? (income>=spend?'On track':'Over income'):'After expenses';
    const goalProgress=state.goal?Math.min(saved/state.goal*100,100):0;$('goalTarget').textContent=money(state.goal);$('goalSaved').textContent=money(saved);$('goalTrack').style.width=goalProgress+'%';$('goalPercent').textContent=Math.round(goalProgress)+'% complete';$('goalRemaining').textContent=money(Math.max(0,state.goal-saved))+' to go';$('goalMessage').textContent=saved>=state.goal?'You reached your savings goal. Great work!':income&&saved>0?'You are '+money(state.goal-saved)+' away from your goal. Keep it going!':'Every rupee saved is a step toward your goal.';
    renderCategories(expenses,spend);renderChart();renderTransactions();
  }
  function renderCategories(expenses,total){const box=$('categoryList');box.innerHTML='';if(!expenses.length){$('categoryEmpty').classList.remove('hidden');return;}$('categoryEmpty').classList.add('hidden');const sums={};expenses.forEach(t=>sums[t.category]=(sums[t.category]||0)+Number(t.amount));Object.entries(sums).sort((a,b)=>b[1]-a[1]).slice(0,5).forEach(([name,value],i)=>{const row=document.createElement('div');row.className='category-row';const pct=total?Math.round(value/total*100):0;row.innerHTML='<div class="category-icon" style="background:'+colors[i%colors.length]+';color:#7668c9">'+(icons[name]||'•')+'</div><div class="category-meta"><div class="category-name-row"><b>'+escapeHtml(name)+'</b><span>'+pct+'%</span></div><div class="category-bar"><i style="width:'+pct+'%"></i></div></div><span class="category-value">'+money(value)+'</span>';box.appendChild(row)});}
  function renderChart(){
    const svg=$('spendChart'),labels=$('xLabels'),month=state.month,ns='http://www.w3.org/2000/svg';svg.innerHTML='';labels.innerHTML='';
    let samples=[];
    if(state.chartRange==='month'){
      const days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();
      const dates=[1,Math.ceil(days*.2),Math.ceil(days*.4),Math.ceil(days*.6),Math.ceil(days*.8),days];
      samples=dates.map(day=>{const cutoff=new Date(month.getFullYear(),month.getMonth(),day);const list=state.transactions.filter(t=>monthKey(t.date)===monthKeyFromDate(month)&&new Date(t.date+'T00:00:00')<=cutoff);return {e:list.filter(t=>t.type==='expense').reduce((s,t)=>s+Number(t.amount),0),i:list.filter(t=>t.type==='income').reduce((s,t)=>s+Number(t.amount),0),label:String(day)}});
    }else{
      for(let i=5;i>=0;i--){const d=new Date(month.getFullYear(),month.getMonth()-i,1),key=monthKeyFromDate(d),list=state.transactions.filter(t=>monthKey(t.date)===key);samples.push({e:list.filter(t=>t.type==='expense').reduce((s,t)=>s+Number(t.amount),0),i:list.filter(t=>t.type==='income').reduce((s,t)=>s+Number(t.amount),0),label:d.toLocaleDateString('en-IN',{month:'short'})})}
    }
    const max=Math.max(100,...samples.flatMap(s=>[s.e,s.i])),ceil=Math.ceil(max/1000)*1000||1000;
    $('yMax').textContent=(ceil/1000).toFixed(ceil>=10000?0:1)+'k';$('yMid').textContent=(ceil/2000).toFixed(ceil>=10000?0:1)+'k';
    const spend=samples.map((s,i)=>(i*700/(samples.length-1))+','+(207-(s.e/ceil)*190)),income=samples.map((s,i)=>(i*700/(samples.length-1))+','+(207-(s.i/ceil)*190));
    labels.innerHTML=samples.map(s=>'<span>'+s.label+'</span>').join('');
    const defs=document.createElementNS(ns,'defs');defs.innerHTML='<linearGradient id="chartGradient" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="#8878e7" stop-opacity=".22"/><stop offset="1" stop-color="#8878e7" stop-opacity="0"/></linearGradient>';svg.appendChild(defs);
    const fill=document.createElementNS(ns,'path');fill.setAttribute('d','M0,220 L'+spend.join(' L')+' L700,220 Z');fill.setAttribute('class','chart-fill');svg.appendChild(fill);
    const line=document.createElementNS(ns,'path');line.setAttribute('d','M'+spend.join(' L'));line.setAttribute('class','line');svg.appendChild(line);
    const il=document.createElementNS(ns,'path');il.setAttribute('d','M'+income.join(' L'));il.setAttribute('class','income-line');svg.appendChild(il);
    spend.forEach(point=>{const xy=point.split(','),c=document.createElementNS(ns,'circle');c.setAttribute('cx',xy[0]);c.setAttribute('cy',xy[1]);c.setAttribute('r','3.5');svg.appendChild(c)});
  }
  function renderTransactions(){const rows=$('transactionRows');rows.innerHTML='';const monthTx=state.transactions.filter(t=>inMonth(t,state.month)).sort((a,b)=>b.date.localeCompare(a.date));const list=state.showAll?monthTx:monthTx.slice(0,5);$('tableEmpty').classList.toggle('hidden',list.length>0);list.forEach(t=>{const tr=document.createElement('tr');const icon=icons[t.category]||'•';tr.innerHTML='<td><div class="transaction-name"><span class="tx-icon '+t.type+'">'+icon+'</span><span>'+escapeHtml(t.note||t.category)+'</span></div></td><td class="category-cell">'+escapeHtml(t.category)+'</td><td>'+fmtDate(t.date)+'</td><td class="amount-col"><span class="amount '+t.type+'">'+(t.type==='income'?'+':'−')+money(t.amount)+'</span><button class="delete-tx" title="Delete transaction" data-id="'+escapeHtml(t.id)+'">×</button></td>';rows.appendChild(tr)});$('viewAll').textContent=state.showAll?'Show less →':'View all →';}
  function escapeHtml(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function updateCategories(){const type=$('transactionType').value,el=$('category');el.innerHTML=categories[type].map(c=>'<option>'+c+'</option>').join('');document.querySelectorAll('.segment').forEach(b=>{b.classList.toggle('selected',b.dataset.type===type);b.classList.toggle('expense-segment',b.dataset.type==='expense')})}
  async function addTransaction(obj){if(state.backend==='sheets'){const res=await request('/api/transactions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(obj)});state.transactions.unshift(res.transaction)}else{obj.id='local-'+Date.now();state.transactions.unshift(obj);persistLocal()}render()}
  async function deleteTransaction(id){if(state.backend==='sheets'&&!String(id).startsWith('demo-')){await request('/api/transactions?id='+encodeURIComponent(id),{method:'DELETE'})}state.transactions=state.transactions.filter(t=>String(t.id)!==String(id));persistLocal();render();toast('Transaction removed')}
  function downloadCsv(){const list=state.transactions.slice().sort((a,b)=>a.date.localeCompare(b.date));const lines=[['Date','Type','Category','Note','Amount'].join(','),...list.map(t=>[t.date,t.type,t.category,t.note||'',t.amount].map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(','))];const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/csv'}));a.download='pennywise-transactions.csv';a.click();URL.revokeObjectURL(a.href);toast('CSV downloaded')}
  document.querySelectorAll('.segment').forEach(b=>b.addEventListener('click',()=>{$('transactionType').value=b.dataset.type;updateCategories()}));document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>closeModal(b.dataset.close)));document.querySelectorAll('.modal-backdrop').forEach(b=>b.addEventListener('click',e=>{if(e.target===b)closeModal(b.id)}));document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.modal-backdrop:not(.hidden)').forEach(m=>closeModal(m.id))});
  ['addTop','emptyAdd'].forEach(id=>$(id).addEventListener('click',()=>{ $('transactionType').value='expense';updateCategories();$('date').value=dateOffset(0);$('formError').classList.add('hidden');openModal('transactionModal')}));$('editGoal').addEventListener('click',()=>{$('goalAmount').value=state.goal;openModal('goalModal')});$('goalAction').addEventListener('click',()=>{$('goalAmount').value=state.goal;openModal('goalModal')});$('goalForm').addEventListener('submit',e=>{e.preventDefault();state.goal=Number($('goalAmount').value)||0;localStorage.setItem('pennywise_goal',String(state.goal));closeModal('goalModal');render();toast('Savings goal updated')});
  $('transactionForm').addEventListener('submit',async e=>{e.preventDefault();$('formError').classList.add('hidden');const item={type:$('transactionType').value,amount:Number($('amount').value),category:$('category').value,date:$('date').value,note:$('note').value.trim()};if(!item.amount||item.amount<=0){showError('Enter an amount greater than zero.');return}try{await addTransaction(item);closeModal('transactionModal');$('transactionForm').reset();$('date').value=dateOffset(0);toast('Transaction saved');}catch(err){showError(err.message||'Could not save. Please try again.')}});
  $('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginError').classList.add('hidden');try{await request('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:$('appPassword').value})});$('loginModal').classList.add('hidden');document.body.style.overflow='';$('appPassword').value='';const data=await request('/api/transactions');state.transactions=data.transactions||[];state.backend='sheets';banner('Connected to your Google Sheet. <strong>Your entries sync across your devices.</strong>');const saved=localStorage.getItem('pennywise_goal');if(saved)state.goal=Number(saved)||20000;render()}catch(err){$('loginError').textContent=err.message;$('loginError').classList.remove('hidden')}});
  $('transactionRows').addEventListener('click',e=>{const b=e.target.closest('.delete-tx');if(b&&confirm('Remove this transaction?'))deleteTransaction(b.dataset.id).catch(err=>toast(err.message))});$('prevMonth').addEventListener('click',()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()-1,1);render()});$('nextMonth').addEventListener('click',()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()+1,1);render()});$('chartRange').addEventListener('change',e=>{state.chartRange=e.target.value;renderChart()});$('viewAll').addEventListener('click',e=>{e.preventDefault();state.showAll=!state.showAll;renderTransactions()});$('exportBtn').addEventListener('click',downloadCsv);$('mobileMenu').addEventListener('click',()=>$('sidebar').classList.toggle('open'));document.querySelectorAll('.nav-item').forEach(a=>a.addEventListener('click',()=>{document.querySelectorAll('.nav-item').forEach(n=>n.classList.remove('active'));a.classList.add('active');$('sidebar').classList.remove('open')}));
  updateCategories();init();
})();
